name: care4parents
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_bloc: ^8.0.1
  flutter_form_bloc: ^0.29.3
  google_fonts: ^2.2.0
  auto_route: ^0.6.9
  json_annotation: ^3.0.1 
  json_serializable: ^3.5.0
  # flutter pub run build_runner watch - generate .g file automatically
  dio: ^4.0.4
  equatable: ^2.0.3
  shared_preferences: ^2.0.11
  connectivity_plus: ^2.2.1
  dartz: ^0.9.2
  get_it: ^5.0.6
  http: ^0.13.4

  dots_indicator: ^1.2.0
  font_awesome_flutter: ^8.11.0
  flutter_svg: ^1.0.0
  # device_info: ^2.0.3
  device_info_plus: ^3.2.2
  pin_code_fields: ^6.1.0
  formz: ^0.3.2
  # hydrated_bloc: ^6.1.0
  

  flutter_html: ^0.8.2
  # flutter_calendar_carousel: ^1.3.18
  table_calendar: ^3.0.3
  permission_handler: ^8.3.0
  #location_web: ^1.0.0
#  location:
  flutter_bluetooth_serial: ^0.4.0
  carousel_slider: ^3.0.0
  image_picker: ^0.8.4+4
  cached_network_image: ^3.2.0
  google_sign_in: ^5.2.4
  syncfusion_flutter_charts: ^18.4.44
  syncfusion_flutter_datepicker: ^18.4.34-beta
  circular_profile_avatar: ^2.0.5
  expansion_tile_card: ^1.1.0
  flutter_pdfview: ^1.2.1
  # file_picker: ^2.1.7
  flutter_document_picker: ^4.0.1
  flutter_icons: ^1.1.0
  url_launcher:
  country_picker: ^1.1.4
  external_app_launcher: ^2.0.2
  firebase_messaging: ^11.2.4
  firebase_database:
  package_info: ^0.4.0+3
  fluttertoast: ^7.1.8
  launch_review: ^3.0.1
  flutter_cached_pdfview:
#  facebook_app_events:
#  razorpay_flutter:
  facebook_app_events: ^0.14.7
  razorpay_flutter: ^1.2.3
  bloc_concurrency: ^0.2.0

  # flutter_facebook_login:
  #  git:
  #     url: https://github.com/sonoo827/flutter_facebook_login
  flutter_login_facebook: ^1.4.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  auto_route_generator: ^0.6.9
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - google_fonts/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
